name: anime_hype
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  share_plus: ^7.2.1 
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - gambar/anime_viral/
    - gambar/beranda/
    - gambar/berita_terbaru/
    - gambar/detail_berita/
    - gambar/login/
    - gambar/profil_pengguna/
    - gambar/rekomendasi/
    - gambar/search/
    - gambar/trending_topik/


  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf